repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.12
    hooks:
      - id: ruff
        args:
          - --fix
          - --config
          - ./api/pyproject.toml
        exclude: migrations/.*$
      - id: ruff-format
        args: [ --config, ./api/pyproject.toml ]
        exclude: migrations/.*$
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args:
          - -c
          - ./api/pyproject.toml
        additional_dependencies:
          - 'bandit[toml]'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.45.0
    hooks:
      - id: eslint
        types: [ file ]
        files: ui/.+[^(\.d)]\.[jt]sx?
        args: [ '--config', 'ui/.eslintrc.cjs', '--fix', '--quiet' ]
        exclude: ".+\\.gen\\.ts$"
        additional_dependencies:
          - eslint@8.45.0
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-react-refresh@0.4.3
          - '@typescript-eslint/eslint-plugin@6.0.0'
          - '@typescript-eslint/parser@6.0.0'
          - '@tanstack/eslint-plugin-query@5.8.4'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: ui/.+\.(json|jsx?|tsx?|html|css|scss)$
        exclude: ".+\\.gen\\.ts$"
        additional_dependencies:
          - prettier@2.7.1
          - '@trivago/prettier-plugin-sort-imports@3.4.0'
          - prettier-plugin-tailwindcss@0.4.1
          - tailwindcss@3.3.3
          - tailwindcss-animate@1.0.7
        args: [ '--config', 'ui/.prettierrc.json' ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: check-merge-conflict
      - id: check-yaml
        exclude: infra/helm/.+/templates/.*
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        args: [ '--verbose' ]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [ '--ignore', 'DL3008' ]
